name: TruffleHog Secret Scan
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at midnight

jobs:
  scan-secrets:
    name: TruffleHog Secrets Scan
    runs-on: [self-hosted, Linux, X64]
    permissions:
      contents: read
      actions: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog-action@main
        with:
          path: ./
          baseDepth: 0
